# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_models', '0004_auto_20170701_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, default=b''),
        ),
    ]
